# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qt5_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(865, 596)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.devices_list = QtWidgets.QTextEdit(self.centralwidget)
        self.devices_list.setMaximumSize(QtCore.QSize(16777215, 325))
        self.devices_list.setObjectName("devices_list")
        self.horizontalLayout.addWidget(self.devices_list)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.user_info = QtWidgets.QPushButton(self.centralwidget)
        self.user_info.setObjectName("user_info")
        self.horizontalLayout_6.addWidget(self.user_info)
        self.show_multichannel_window = QtWidgets.QPushButton(self.centralwidget)
        self.show_multichannel_window.setObjectName("show_multichannel_window")
        self.horizontalLayout_6.addWidget(self.show_multichannel_window)
        self.show_window = QtWidgets.QPushButton(self.centralwidget)
        self.show_window.setObjectName("show_window")
        self.horizontalLayout_6.addWidget(self.show_window)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.context_status_label = QtWidgets.QLabel(self.centralwidget)
        self.context_status_label.setObjectName("context_status_label")
        self.verticalLayout.addWidget(self.context_status_label)
        self.quality_status_label = QtWidgets.QLabel(self.centralwidget)
        self.quality_status_label.setWordWrap(True)
        self.quality_status_label.setObjectName("quality_status_label")
        self.verticalLayout.addWidget(self.quality_status_label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.start_recording = QtWidgets.QPushButton(self.centralwidget)
        self.start_recording.setObjectName("start_recording")
        self.horizontalLayout_2.addWidget(self.start_recording)
        self.stop_recording = QtWidgets.QPushButton(self.centralwidget)
        self.stop_recording.setObjectName("stop_recording")
        self.horizontalLayout_2.addWidget(self.stop_recording)
        self.start_playback = QtWidgets.QPushButton(self.centralwidget)
        self.start_playback.setObjectName("start_playback")
        self.horizontalLayout_2.addWidget(self.start_playback)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.search = QtWidgets.QPushButton(self.centralwidget)
        self.search.setObjectName("search")
        self.horizontalLayout_11.addWidget(self.search)
        self.device_combo = QtWidgets.QComboBox(self.centralwidget)
        self.device_combo.setObjectName("device_combo")
        self.horizontalLayout_11.addWidget(self.device_combo)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_11.addWidget(self.pushButton)
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setObjectName("exit")
        self.horizontalLayout_11.addWidget(self.exit)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.search.clicked.connect(MainWindow.search_click) # type: ignore
        self.exit.clicked.connect(MainWindow.close) # type: ignore
        self.pushButton.clicked.connect(MainWindow.connect_semg_click) # type: ignore
        self.show_window.clicked.connect(MainWindow.show_window_click) # type: ignore
        self.show_multichannel_window.clicked.connect(MainWindow.show_multichannel_window_click) # type: ignore
        self.user_info.clicked.connect(MainWindow.user_info_click) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "肌电手环采集程序"))
        self.label_2.setText(_translate("MainWindow", "设备列表："))
        self.user_info.setText(_translate("MainWindow", "录入采集信息"))
        self.show_multichannel_window.setText(_translate("MainWindow", "多窗口显示"))
        self.show_window.setText(_translate("MainWindow", "单窗口显示"))
        self.context_status_label.setText(_translate("MainWindow", "采集信息：未录入"))
        self.quality_status_label.setText(_translate("MainWindow", "质量检查：尚未执行"))
        self.start_recording.setText(_translate("MainWindow", "开始采集"))
        self.stop_recording.setText(_translate("MainWindow", "停止采集"))
        self.start_playback.setText(_translate("MainWindow", "数据回放"))
        self.search.setText(_translate("MainWindow", "搜索设备"))
        self.pushButton.setText(_translate("MainWindow", "连接"))
        self.exit.setText(_translate("MainWindow", "退出"))
        self.menu.setTitle(_translate("MainWindow", "采集程序"))
