# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_on_time_show_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(659, 522)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.wave_guide_show = PlotWidget(Dialog)
        self.wave_guide_show.setObjectName("wave_guide_show")
        self.listWidget = QtWidgets.QListWidget(self.wave_guide_show)
        self.listWidget.setGeometry(QtCore.QRect(530, 0, 111, 141))
        self.listWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.listWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget.addItem(item)
        self.horizontalLayout.addWidget(self.wave_guide_show)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Dialog", "所有通道"))
        item = self.listWidget.item(1)
        item.setText(_translate("Dialog", "通道1"))
        item = self.listWidget.item(2)
        item.setText(_translate("Dialog", "通道2"))
        item = self.listWidget.item(3)
        item.setText(_translate("Dialog", "通道3"))
        item = self.listWidget.item(4)
        item.setText(_translate("Dialog", "通道4"))
        item = self.listWidget.item(5)
        item.setText(_translate("Dialog", "通道5"))
        item = self.listWidget.item(6)
        item.setText(_translate("Dialog", "通道6"))
        item = self.listWidget.item(7)
        item.setText(_translate("Dialog", "通道7"))
        item = self.listWidget.item(8)
        item.setText(_translate("Dialog", "通道8"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
from pyqtgraph import PlotWidget
