# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_patient_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(460, 360)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_title = QtWidgets.QLabel(Dialog)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.gridLayout.addWidget(self.label_title, 0, 0, 1, 2)
        self.label_subject = QtWidgets.QLabel(Dialog)
        self.label_subject.setObjectName("label_subject")
        self.gridLayout.addWidget(self.label_subject, 1, 0, 1, 1)
        self.user_name = QtWidgets.QLineEdit(Dialog)
        self.user_name.setObjectName("user_name")
        self.gridLayout.addWidget(self.user_name, 1, 1, 1, 1)
        self.label_side = QtWidgets.QLabel(Dialog)
        self.label_side.setObjectName("label_side")
        self.gridLayout.addWidget(self.label_side, 2, 0, 1, 1)
        self.side = QtWidgets.QComboBox(Dialog)
        self.side.setObjectName("side")
        self.gridLayout.addWidget(self.side, 2, 1, 1, 1)
        self.label_action = QtWidgets.QLabel(Dialog)
        self.label_action.setObjectName("label_action")
        self.gridLayout.addWidget(self.label_action, 3, 0, 1, 1)
        self.action = QtWidgets.QComboBox(Dialog)
        self.action.setObjectName("action")
        self.gridLayout.addWidget(self.action, 3, 1, 1, 1)
        self.label_experiment = QtWidgets.QLabel(Dialog)
        self.label_experiment.setObjectName("label_experiment")
        self.gridLayout.addWidget(self.label_experiment, 4, 0, 1, 1)
        self.experiment_id = QtWidgets.QLineEdit(Dialog)
        self.experiment_id.setObjectName("experiment_id")
        self.gridLayout.addWidget(self.experiment_id, 4, 1, 1, 1)
        self.label_time = QtWidgets.QLabel(Dialog)
        self.label_time.setObjectName("label_time")
        self.gridLayout.addWidget(self.label_time, 5, 0, 1, 1)
        self.collect_time = QtWidgets.QDateTimeEdit(Dialog)
        self.collect_time.setReadOnly(True)
        self.collect_time.setObjectName("collect_time")
        self.gridLayout.addWidget(self.collect_time, 5, 1, 1, 1)
        self.save = QtWidgets.QPushButton(Dialog)
        self.save.setObjectName("save")
        self.gridLayout.addWidget(self.save, 6, 0, 1, 2)

        self.retranslateUi(Dialog)
        self.save.clicked.connect(Dialog.save_click) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "采集信息录入"))
        self.label_title.setText(_translate("Dialog", "本次采集信息"))
        self.label_subject.setText(_translate("Dialog", "受试者标识"))
        self.user_name.setPlaceholderText(_translate("Dialog", "仅用于生成匿名编号，不保存明文"))
        self.label_side.setText(_translate("Dialog", "佩戴侧"))
        self.label_action.setText(_translate("Dialog", "本次动作"))
        self.label_experiment.setText(_translate("Dialog", "实验编号"))
        self.label_time.setText(_translate("Dialog", "录入时间"))
        self.save.setText(_translate("Dialog", "确定"))
